apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v9kqyvq30-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v9kqyvq30-java-quarkus-gitops